services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ts_app
    ports:
      - "1107:1107"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/project

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
